DemoProject/Models/Person.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DemoProject.Models
{
    [Table("Person")]
    public class Person : ModelBase
    {
        public Person()
        {
            Addresses = new List<Address>();
            Contacts = new List<Contact>();
        }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "First Name is required.")]
        [DataType(DataType.Text)]
        [StringLength(250, MinimumLength = 1, ErrorMessage = "First Name is not a valid length.")]
        public string FirstName { get; set; }

        [DisplayName("Second Name")]
        [DataType(DataType.Text)]
        [StringLength(250, MinimumLength = 1, ErrorMessage = "Second Name is not a valid length.")]
        public string SecondName { get; set; }

        [DisplayName("Surname")]
        [Required(ErrorMessage = "Surname is required.")]
        [DataType(DataType.Text)]
        [StringLength(250, MinimumLength = 1, ErrorMessage = "Surname is not a valid length.")] 
        public string Surname { get; set; }

        
        public List<Address> Addresses { get; set; }

        public List<Contact> Contacts { get; set; }
    }
}

DemoProject/Controllers/AddressesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DemoProject.Data;
using DemoProject.Extensions;
using DemoProject.Models;

namespace DemoProject.Controllers
{
    public class AddressesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AddressesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // Get: Addresses For Person
        public async Task<IActionResult> Index(Guid? personId)
        {
            if (!personId.HasValue)
            {
                return View(new Person());
            }

            var person = await _context.Person.FirstOrDefaultAsync(p => p.Id == personId);
            if(person == null)
            {
                return NotFound();
            }

            person.Addresses = _context.Address.Where(a => a.PersonId == person.Id).ToList();

            return View(person);
        }

        // GET: Addresses/Details/
        public async Task<IActionResult> Details(Guid? addressId)
        {
            if (!addressId.HasValue)
            {
                return NotFound();
            }

            var address = await _context.Address.FirstOrDefaultAsync(m => m.Id == addressId);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // GET: Addresses/Create
        public IActionResult Create(Guid? personId)
        {
            return View(new Address { PersonId = personId.GetValueOrDefault() });
        }

        // POST: Addresses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Line1,Line2,Town,County,Postcode,DateUsedFrom,DateUsedTo,IsCorrespondence,IsBilling,IsActive,PersonId")] Address address)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    address.SetCreateDefaultSettings();
                    _context.Add(address);
                    await _context.SaveChangesAsync();
                    
                    return RedirectToAction("Index", new { personId = address.PersonId });
                }
                catch (Exception e)
                {
                    return BadRequest(e);
                }
            }

            return View(null);
        }

        // GET: Addresses/Edit/
        public async Task<IActionResult> Edit(Guid? addressId)
        {
            if (addressId == null)
            {
                return NotFound();
            }

            var address = await _context.Address.FindAsync(addressId);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // POST: Addresses/Edit/
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Line1,Line2,Town,County,Postcode,DateUsedFrom,DateUsedTo,IsCorrespondence,IsBilling,Id,CreatedOn,IsActive,PersonId")] Address address)
        {
            if (id != address.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(address);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AddressExists(address.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { personId = address.PersonId });
            }

            return View(address);
        }

        // GET: Addresses/Delete/
        public async Task<IActionResult> Delete(Guid? addressId)
        {
            if (addressId == null)
            {
                return NotFound();
            }

            var address = await _context.Address.FirstOrDefaultAsync(m => m.Id == addressId);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // POST: Addresses/Delete/
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            Guid? personId;
            try
            {
                var address = await _context.Address.FindAsync(id);
                personId = address.PersonId;
                _context.Address.Remove(address);
                await _context.SaveChangesAsync();
            }
            catch (Exception e)
            {
                return BadRequest(e);
            }

            return RedirectToAction("Index", new { personId = personId.GetValueOrDefault() });
        }

        private bool AddressExists(Guid id)
        {
            return _context.Address.Any(e => e.Id == id);
        }
    }
}

DemoProject/Controllers/EmailContactsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DemoProject.Data;
using DemoProject.Models;

namespace DemoProject.Controllers
{
    public class EmailContactsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmailContactsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: EmailContacts
        public async Task<IActionResult> Index()
        {
            return View(await _context.EmailContact.ToListAsync());
        }

        // GET: EmailContacts/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emailContact = await _context.EmailContact
                .FirstOrDefaultAsync(m => m.Id == id);
            if (emailContact == null)
            {
                return NotFound();
            }

            return View(emailContact);
        }

        // GET: EmailContacts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EmailContacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmailAddress,IsMarketable,DateUsedFrom,DateUsedTo,Id,CreatedOn,IsActive")] EmailContact emailContact)
        {
            if (ModelState.IsValid)
            {
                emailContact.Id = Guid.NewGuid();
                _context.Add(emailContact);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(emailContact);
        }

        // GET: EmailContacts/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emailContact = await _context.EmailContact.FindAsync(id);
            if (emailContact == null)
            {
                return NotFound();
            }
            return View(emailContact);
        }

        // POST: EmailContacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("EmailAddress,IsMarketable,DateUsedFrom,DateUsedTo,Id,CreatedOn,IsActive")] EmailContact emailContact)
        {
            if (id != emailContact.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(emailContact);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmailContactExists(emailContact.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(emailContact);
        }

        // GET: EmailContacts/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emailContact = await _context.EmailContact
                .FirstOrDefaultAsync(m => m.Id == id);
            if (emailContact == null)
            {
                return NotFound();
            }

            return View(emailContact);
        }

        // POST: EmailContacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var emailContact = await _context.EmailContact.FindAsync(id);
            _context.EmailContact.Remove(emailContact);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmailContactExists(Guid id)
        {
            return _context.EmailContact.Any(e => e.Id == id);
        }
    }
}

DemoProject/Controllers/PeopleController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DemoProject.Data;
using DemoProject.Extensions;
using DemoProject.Models;

namespace DemoProject.Controllers
{
    public class PeopleController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PeopleController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: People
        public async Task<IActionResult> Index()
        {
            return View(await _context.Person.ToListAsync());
        }

        // GET: People/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person.FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,SecondName,Surname,Id")] Person person)
        {
            if (ModelState.IsValid)
            {
                person.SetCreateDefaultSettings();
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(person);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("FirstName,SecondName,Surname,Id,IsActive,CreatedOn")] Person person)
        {
            if (id != person.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var person = await _context.Person.FindAsync(id);
            _context.Person.Remove(person);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonExists(Guid id)
        {
            return _context.Person.Any(e => e.Id == id);
        }
    }
}

DemoProject/Views/People/Create.cshtml
@model Person

@{
    ViewData["Title"] = "Create Person";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create new person record</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondName" class="control-label"></label>
                <input asp-for="SecondName" class="form-control" />
                <span asp-validation-for="SecondName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <input type="button" value="Back to List" class="btn btn-primary" onclick="location.href = '@Url.Action("Index", "People")'" />
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoProject/Views/People/Delete.cshtml
@model DemoProject.Models.Person

@{
    ViewData["Title"] = "Delete Person";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete this person record?</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DemoProject/Views/People/Details.cshtml
@model Person

@{
    ViewData["Title"] = "Details of Person";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details held for person record</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SecondName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
</div>
<div>
    <input type="button" value="View Addresses" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Addresses", new { personId = Model.Id})'" /> |
    <input type="button" value="View Email Addresses" class="btn btn-primary" onclick="location.href = '@Url.Action("Index", "EmailContacts")'" /> |
    <input type="button" value="View Telephone Numbers" class="btn btn-primary" onclick="location.href = '@Url.Action("Index", "TelephoneContacts")'" /> |
    <input type="button" value="Edit Person Record" class="btn btn-primary" onclick="location.href = '@Url.Action("Edit", "People", new { id = Model.Id})'" /> |
    <input type="button" value="Back to List" class="btn btn-primary" onclick="location.href = '@Url.Action("Index", "People")'" />
</div>
<div>
    @if (!Model.IsActive)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("Record INACTIVE!");
            };
        </script>
    }
</div>

DemoProject/Views/People/Edit.cshtml
@model Person

@{
    ViewData["Title"] = "Edit a person";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editing person record</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondName" class="control-label"></label>
                <input asp-for="SecondName" class="form-control" />
                <span asp-validation-for="SecondName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CreatedOn" />
            <div>
                @Html.DisplayNameFor(model => model.CreatedOn)
                @Html.DisplayFor(model => model.CreatedOn)
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        
    </div>
</div>

<div>
    <input type="button" value="Back to List" class="btn btn-primary" onclick="location.href = '@Url.Action("Index", "People")'" />
</div>
<div>
    @if (!Model.IsActive)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("Record INACTIVE!");
            };
        </script>
    }
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoProject/Views/People/Index.cshtml
@model IEnumerable<Person>

@{
    ViewData["Title"] = "People";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List of people in the database</h1>

<p>
    <input type="button" value="Create New Person" class="btn btn-primary" onclick="location.href = '@Url.Action("Create", "People")'" />
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>